language: python

python:
   - "3.5"

sudo: true

install:
    - pip install --upgrade pip
    - pip --version
    - pip install requests
    - pip install coverage
    - pip install pylint
    - pip install autopep8

script:
    - psql -d postgres -f db_init.sql


before_script:
    - uname -a
    - printenv
    - pip list
    - coverage --version
    - pylint   --version

script:
    - date
    - ls -al
    - make test



