FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Komixx

Komixx is provides an interactive experience in exploring the comic book world. Users can search through Characters, Teams Volumes, and Publishers through the comic book world.


## Characters [/characters]
### List All Characters [GET]

+ Response 200 (application/json)

## Characters [/characters/id]
### List a Single Character [GET]

+ Response 200 (application/json)

## Teams [/teams]
### List All Teams [GET]

+ Response 200 (application/json)

## Teams [/teams/id]
### List a Single Team [GET]

+ Response 200 (application/json)

## Volumes [/volumes]
### List All Volumes [GET]

+ Response 200 (application/json)

## Volumes [/volumes/id]
### List a Single Volume [GET]

+ Response 200 (application/json)

## Publishers Collection [/publishers]
### List All Publishers [GET]

+ Response 200 (application/json)

## Publishers Collection [/publishers/id]
### List a Single Publisher [GET]

+ Response 200 (application/json)