FORMAT: 1A
HOST: http://downing.rocks/

# Komixx

Komixx provides an interactive experience in exploring the comic book world. Users can search through Characters, Teams, Volumes, and Publishers through the comic book world.


## Characters [/api/characters]
### List All Characters [GET]

+ Response 200 (application/json)

        
        {
            "result": [
                {
                    "gender": [
                        "Female"
                    ],
                    "image": [
                        "http://comicvine.gamespot.com/api/image/scale_small/1044725-mm.jpg"
                    ],
                    "name": ["Jerry"],
                    "publisher": [
                        "Dell"
                    ],
                    "real_name": [
                        null
                    ]
                },
                {
                    "gender": [null],
                    "image": [null],
                    "name": ["Terry"],
                    "publisher": [null],
                    "real_name": [null]
                }
            ]
        }
        
## Characters [/api/character/name]
### List a Single Character [GET]

+ Response 200 (application/json)

        {
            "result": [
                {
                    "gender": [null],
                    "image": [null],
                    "name": "Terry",
                    "publisher": [null],
                    "real_name": [null],
                    "teams": [{"image": "imageURL", "name": "Team  Name"}],
                    "volumes": [{"image": "imageURL", "name": "Volume  Name"}]
                }
            ]
        }
## Teams [/api/teams]
### List All Teams [GET]

+ Response 200 (application/json)

        {
            "result": 
            [
                {
                    "appear": ["Mad 176-179"],
                    "image": ["http://comicvine.gamespot.com/api/image/scale_small/367187-154544-ewoks.JPG"],
                    "name": ["Ewoks"],
                    "num_appearances": ["0"],
                    "publisher": ["Dark Horse Comics"]
                },
                {
                    "appear": ["Season of Mists: Prologue"],
                    "image": ["http://comicvine.gamespot.com/api/image/scale_small/94443-54950-the-endless.jpg"],
                    "name": ["The Endless"],
                    "num_appearances": ["0"],
                    "publisher": ["Vertigo"]
                }
            ]
        }



## Teams [/api/teams/nameOfTeam]
### List a Single Team [GET]

+ Response 200 (application/json)

        {
            "result": {
                "appear": "And The Horse You Rode In On",
                "description": " ",
                "image": "imageURL",
                "name": "Adephi",
                "num_appearances": "0",
                "publisher_name": "Vertigo",
                "team_characters": [
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/667207-002.jpg",
                        "name": "DeBlanc"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/85587-48659-mathias.jpg",
                        "name": "Mathias"
                    }
                ],
                "team_volumes": [
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/2032970-01.jpg",
                        "name": "Preacher"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/990379-vol1.jpg",
                        "name": "Preacher: Gone to Texas"
                    }
                ]
            }
        }




## Volumes [/api/volumes]
### List All Volumes [GET]

+ Response 200 (application/json)

        {
            "result": 
            {
                "image": ["http://comicvine.gamespot.com/api/image/scale_small/777681-1.jpg"],
                "name": ["100 Bullets"],
                "num_issues": ["100"],
                "publisher": ["Vertigo"],
                "start_year": [1999]
            },
            {
                "description": ["None"],
                "image": ["http://comicvine.gamespot.com/api/image/scale_small/2199272-01.jpg"],
                "name": ["The Sandman"],
                "num_issues": ["75"],
                "publisher_name": ["Vertigo"],
                "start_year": [1989]
            }
        }


## Volumes [/api/volumes/volumeName]
### List a Single Volume [GET]

+ Response 200 (application/json)

        {
            "result": {
                "description": "None",
                "image": "http://comicvine.gamespot.com/api/image/scale_small/2199272-01.jpg",
                "name": "The Sandman",
                "num_issues": "75",
                "publisher_name": "Vertigo",
                "start_year": 1989,
                "volume_characters": [
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/1291971-ac894.jpg",
                        "name": "Death of the Endless"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/81662-181730-delirium.jpg",
                        "name": "Delirium of the Endless"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/447795-danielhall.jpg",
                        "name": "Daniel Hall"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/749044-2_desire.jpg",
                        "name": "Desire of the Endless"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/438765-thesandman_despair_4_11_07.jpg",
                        "name": "Despair of the Endless"
                    }
                ],
                "volume_teams": [
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/94443-54950-the-endless.jpg",
                        "name": "The Endless"
                    }
                ]
            }
        }



## Publishers Collection [/api/publishers]
### List All Publishers [GET]

+ Response 200 (application/json)

        {
            "result": 
            {
                "address": ["1745 Broadwa"],
                "city": ["New York"],
                "image": ["http://static4.comicvine.com/uploads/scale_small/6/69951/1387447-logo.gif?api_key=d1fcd2dc19ac4cbac24fd26d5161210b150cbaed&format=json"],
                "name": ["Dell"],
                "state": ["New York"]
            },
            {
                "address": [null],
                "city": [null],
                "image": ["http://static4.comicvine.com/uploads/scale_small/6/69951/1387073-fiction_house.jpg?api_key=d1fcd2dc19ac4cbac24fd26d5161210b150cbaed&format=json"],
                "name": ["Fiction House"],
                "state": [null]
            }
        }

## Publishers Collection [/api/publishers/publisherName]
### List a Single Publisher [GET]

+ Response 200 (application/json)

        {
            "result": {
                "address": null,
                "city": null,
                "deck": "A pulp magazine and comic book publisher in the Golden Age of Comics.",
                "image": "http://static4.comicvine.com/uploads/scale_small/6/69951/1387073-fiction_house.jpg?api_key=d1fcd2dc19ac4cbac24fd26d5161210b150cbaed&format=json",
                "name": "Fiction House",
                "publisher_characters": [
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/1387237-reef_ryan.jpg",
                        "name": "Reef Ryan"
                    }
                ],
                "publisher_teams": [
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/1617886-phantom_falcons.jpg",
                        "name": "Phantom Falcons"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/1616246-royal_watch_rangers_comics_1.jpg",
                        "name": "Royal Watch"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/1618095-captain_morgans_us_rangers.jpg",
                        "name": "Captain Morgan's US Rangers"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/2181282-spacerangers.jpg",
                        "name": "Space Rangers"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/1616251-defense_patrol.jpg",
                        "name": "Defense Patrol"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/1616179-rangers_of_freedom.jpg",
                        "name": "Rangers of Freedom"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/1618131-captain_morgans_sky_rangers.jpg",
                        "name": "Captain Morgans Sky Rangers"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/1699406-white_hunters_of_the_african_safari.jpg",
                        "name": "White Hunters of the African Safari"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/1699404-captain_thunder_and_his_congo_lancers.jpg",
                        "name": "Congo Lancers"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/1619465-crusoe_island.jpg",
                        "name": "Crusoe Island"
                    }
                ],
                "publisher_volumes": [
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/225367-19564-116993-1-jungle-comics.jpg",
                        "name": "Jungle Comics"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/1618484-8.jpg",
                        "name": "Rangers Comics"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/1618451-1.jpg",
                        "name": "Rangers of Freedom Comics"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/3424103-01.jpg",
                        "name": "Roy Thomas Presents Planet Comics"
                    },
                    {
                        "image": "http://comicvine.gamespot.com/api/image/scale_small/4641116-1441336221-0.jpg.jpg",
                        "name": "Planet Comics"
                    }
                ],
                "state": null
            }
        }